version: '3'
services:
  
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 4001:4001
  
  frontend:
    build: 
      context: ./frontend
      args:
        - DOMAIN=${DOMAIN}
        - PORT=${PORT}
    container_name: frontend
    ports:
      - 80:80